accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^Signup/$',views.signup_view,name='signup'),
    url(r'^Login/$',views.login_view,name="login"),
    url(r'^Logout/$',views.logout_view,name="logout"),

]

poll/urls.py
from django.conf.urls import url
from . import views

app_name = 'poll'
urlpatterns = [
    url('create/', views.create, name='create'),
    url('vote/(?P<poll_id>\d+)/', views.vote, name='vote'),
    url('results/(?P<poll_id>\d+)/', views.results, name='results'),
    url('edit/(?P<poll_id>\d+)/', views.edit, name='edit'),
    url('delete/(?P<poll_id>\d+)/', views.delete, name='delete'),
    url('', views.home, name='home'),
]

polling/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from poll import views as poll_views

urlpatterns = [
    url('admin/', admin.site.urls),
    url('accounts/',include('accounts.urls')),
    url('',include('poll.urls')),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

poll/models.py
from django.db import models
from django.contrib.auth.models import User

class Poll(models.Model):
    question = models.TextField()
    options = models.JSONField(default=list)
    options_count = models.JSONField(default=list)

    def __str__(self):
        return self.question

    def snippet(self):
        return self.question[:80]

class Vote(models.Model):
    name = models.ForeignKey(User,on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll,on_delete=models.CASCADE)
    status = models.BooleanField(default=False)
    chosen = models.CharField(blank=True,null=True,max_length=200)

    def __str__(self):
        return self.chosen

accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.contrib.auth import login,logout
# Create your views here.

def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)
            return redirect('poll:home')
    else:
        form = UserCreationForm()
    return render(request,'signup.html',{'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request,user)
            if 'next'in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('poll:home')
    else:
        form = AuthenticationForm()
    return render(request,'login.html',{'form':form})

def logout_view(request):
    logout(request)
    return redirect('poll:home')

poll/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
import json
from .models import Poll,Vote

def home(request):
    voted_id=[]
    voted=[]
    if request.user.is_authenticated:
        voted = Vote.objects.filter(name=request.user,status=True)
        for each in voted:
            voted_id.append(each.poll.id)

    if len(voted)>0:
        polls = Poll.objects.filter().exclude(id__in=voted_id)
    else:
        polls = Poll.objects.all()

    context = {'polls': polls,'voted':voted}
    return render(request, 'home.html', context)

@login_required(login_url="/accounts/Login/")
def create(request):
    if request.method == 'POST':
        jsondata = json.loads(request.body)
        question = jsondata['question']
        options = jsondata['options']
        options_count = [0]*len(options)
        poll = Poll()
        poll.question=question
        poll.options=options
        poll.options_count=options_count
        poll.save()
        return redirect('poll:home')

    return render(request, 'create.html')

@login_required(login_url="/accounts/Login/")
def edit(request,poll_id):
    poll = Poll.objects.get(pk=poll_id)
    if request.method == 'POST':
        jsondata = json.loads(request.body)
        question = jsondata['question']
        options = jsondata['options']
        options_count = [0]*len(options)

        Vote.objects.filter(poll=poll).delete()

        poll.question=question
        poll.options=options
        poll.options_count=options_count
        poll.save()

        return redirect('poll:home')

    context = {'poll': poll}
    return render(request, 'edit.html', context)

@login_required(login_url="/accounts/Login/")
def vote(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)

    if request.method == 'POST':
        selected_option = request.POST['poll']
        if selected_option:
            poll.options_count[int(selected_option)-1] += 1
            poll.save()
            voted = Vote()
            voted.name=request.user
            voted.poll=poll
            voted.status=True
            voted.chosen=poll.options[int(selected_option)-1]
            voted.save()
        else:
            return HttpResponse(400, 'Invalid form')

        return redirect('poll:results', poll.id)

    context = {'poll' : poll}
    return render(request, 'vote.html', context)

@login_required(login_url="/accounts/Login/")
def delete(request, poll_id):
    Poll.objects.get(pk=poll_id).delete()
    return redirect('poll:home')

def results(request, poll_id):
    poll = Poll.objects.get(pk=poll_id)
    options = zip(poll.options,poll.options_count)
    total = sum(poll.options_count)
    percent = []
    for count in poll.options_count:
        if count>0:
            percent.append(int((count / total) * 100))
        else:
            percent.append(0)

    option_percent = zip(poll.options,percent)
    maxpoll="no votings...!"
    if total>0:
        maxpoll = poll.options[poll.options_count.index(max(poll.options_count))]
    context = {'poll' : poll,'options' : options,'total':total,'percent':percent,'option_percent':option_percent,'maxpoll':maxpoll}
    return render(request, 'results.html', context)

accounts/templates/login.html
{% extends 'base_layout.html' %}
{% block main %}
<h3 class="container">Login</h3>
<form class="site-form container" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{form}}
    {% if request.GET.next %}
        <input type="hidden" name="next" value="{{request.GET.next}}">
    {% endif %}
    <br>
    <input class="btn btn-warning" type="submit" value="Login">
</form>
{% endblock %}

accounts/templates/signup.html
{% extends 'base_layout.html' %}
{% block main %}
<h3 class="container">Sign up</h3>
<form class="site-form container" action="{% url 'accounts:signup' %}" method="post">
    {% csrf_token %}
    {{form}}
    <br>
    <input class="btn btn-warning" type="submit" value="Signup">
</form>
{% endblock %}

poll/templates/base_layout.html
{% load static %}
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>{% block title %}{% endblock %}</title>

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

	</head>
	<script>
        function getToken(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
        var csrftoken = getToken('csrftoken')
	</script>
	<body>
		<nav class="navbar navbar-default" role="navigation">
			<div class="container">

				<div class="navbar-header">
					<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
						<span class="sr-only">Toggle navigation</span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
						<span class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'poll:home' %}">Poll App</a>
				</div>

					<ul class="nav navbar-nav">
						{% if user.is_authenticated %}
							<li class="navbar-brand"><b>{{user}}</b></li>
						{% else %}
							<li class="navbar-brand"><b>User</b></li>
						{% endif %}
							<li><a href="{% url 'poll:home' %}">Home</a></li>
						{% if user.is_superuser %}
							<li><a href="{% url 'poll:create' %}">Create</a></li>
						{% endif %}
					</ul>
					<ul class="nav navbar-nav pull-right">
						{% if user.is_authenticated %}
	     	            	<li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                     	{% else %}
                        	<li><a href="{% url 'accounts:login' %}">Login</a></li>
                        	<li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                     	{% endif %}
					</ul>
				</div>
		</nav>

		<div class="main-container">
			{% block main %}{% endblock %}
		</div>
	</body>
</html>

poll/templates/create.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}Create Poll{% endblock %}

{% block main %}
<script src="{% static 'poll.js'%}"></script>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">

            <div class="panel-heading">
                <h3 class="panel-title" id="title">Create A New Poll</h3>
            </div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="question">Enter Poll Question</label>
                            <input type="text" class="form-control" id="question">
                        </div>
                    </div>
                </div>

                <a class="btn btn-info" id="add">Add Option</a>&nbsp;&nbsp;&nbsp;
                <a class="btn btn-info" id="remove">Remove Option</a>
                <br><br>

                <div id="AddOption">
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input type="text" class="form-control opt">
                            </div>
                        </div>
                    </div>
                </div>

                <div class="row">
                    <hr />
                    <div class="col-lg-4">
                        <button class="btn btn-info" id="create">Submit</button>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

poll/templates/edit.html
{% extends "base_layout.html" %}
{% load static %}
{% block title %}Edit Poll{% endblock %}

{% block main %}
<script src="{% static 'poll.js'%}"></script>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">

            <div class="panel-heading">
                <h3 class="panel-title">Edit Post <b id="title">{{poll.id}}</b></h3>
            </div>
            <div class="panel-body">

                <div class="row">
                    <div class="col-lg-12">
                        <div class="form-group">
                            <label for="question">Poll Question</label>
                            <input type="text" class="form-control" id="question" value="{{poll.question}}">
                        </div>
                    </div>
                </div>

                <a class="btn btn-info" id="add">Add Option</a>&nbsp;&nbsp;&nbsp;
                <a class="btn btn-info" id="remove">Remove Option</a>
                <br><br>

                <div id="AddOption">
                    {% for option in poll.options %}
                    <div class="row">
                        <div class="col-lg-4">
                            <div class="form-group">
                                <input type="text" class="form-control opt" value="{{option}}">
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="row">
                    <hr />
                    <div class="col-lg-4">
                        <button class="btn btn-info" id="create">Save</button>
                    </div>
                </div>

            </div>

        </div>
    </div>
</div>
{% endblock %}

poll/templates/home.html
{% extends "base_layout.html" %}

{% block title %}Homepage{% endblock %}

{% block main %}
<script>
$(document).on("click",".voted",function(){
    if($(this).parent().parent().next().css('display').toLowerCase()=='none') {
         $(this).parent().parent().next().css('display','block');
    }
    else {
        $(this).parent().parent().next().css('display','none')
    }
});

</script>
<div class="row">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Available Polls</h3>
            </div>

            <ul class="list-group home">
                {% for vote in voted %}
                <li class="list-group-item ">
                    <strong>{{ vote.poll.snippet }}</strong>
                    <span class="pull-right">
                        {% if user.is_superuser %}
                            <a href="{% url 'poll:edit' vote.poll.id %}" class="btn btn-info btn-xs">Edit</a>
                            <a href="{% url 'poll:delete' vote.poll.id %}" class="btn btn-info btn-xs">Delete</a>
                        {% endif %}
                        <a class="voted btn btn-default btn-xs">voted</a>
                        <a href="{% url 'poll:results' vote.poll.id %}" class="btn btn-default btn-xs">View Results</a> &nbsp;
                    </span>
                </li>
                <li class="list-group-item vote-detail" style="display:none;">
                    <p class="opt-voted">
                        {% for option in vote.poll.options %}
                            <label>{{forloop.counter}}. {{ option }}</label> &nbsp;
                        {% endfor %}
                    </p>
                    <b class="pull-right" style="color:green;">selected: {{vote.chosen}}</b><br>
                </li>
                {% endfor %}

                {% for poll in polls %}
                <li class="list-group-item">
                    <strong>{{ poll.snippet }}</strong>
                    <span class="pull-right">
                        {% if user.is_superuser %}
                            <a href="{% url 'poll:edit' poll.id %}" class="btn btn-info btn-xs">Edit</a>
                            <a href="{% url 'poll:delete' poll.id %}" class="btn btn-info btn-xs">Delete</a>
                            <a href="{% url 'poll:vote' poll.id %}" class="btn btn-info btn-xs">Vote</a>
                        {% elif user.is_authenticated %}
                            <a href="{% url 'poll:vote' poll.id %}" class="btn btn-info btn-xs">Vote</a>
                        {% endif %}&nbsp;
                        <a href="{% url 'poll:results' poll.id %}" class="btn btn-default btn-xs">View Results</a> &nbsp;
                    </span>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

poll/templates/results.html
{% extends "base_layout.html" %}

{% block title %}Results{% endblock %}

{% block main %}
<div class="row">
    <div class="col-lg-8 col-lg-offset-2 ">
        <div class="panel-heading">
                <h3 class="panel-title">Poll Result</h3>
        </div>
        <div class="panel panel-default result">
            <div class="panel-body">
                <h4>Max Poll: {{ maxpoll }}</h4>
            </div>
            <div class="barchart">
                <table id="bar-table">
                    {% for option,percent in option_percent %}
                    <tr>
                        <td class="barchart-col1">{{option}}</td>
                        <td>
                            <div class="container-bar">
                                 <div class="skills" style="width:{{percent}}%;background-color:green;">{{percent}}%</div>
                            </div>
                        </td>
                    </tr>
                    {% endfor %}
                </table>
            </div>
            <div class="panel-body">
                <h4>{{ poll.question }}</h4>
            </div>
            <ul class="list-group">
                {% for option,count in options %}
                    <li class="list-group-item">{{ option }} &mdash; <strong>{{ count }}</strong></li>
                {% endfor%}
            </ul>
            <div class="panel-footer">
                Total &mdash; <strong>{{total}}</strong>
            </div>
        </div>
    </div>
</div>

{% endblock %}

poll/templates/vote.html
{% extends "base_layout.html" %}

{% block title %}Vote{% endblock %}

{% block main %}
<div class="row vote">
    <div class="col-lg-8 col-lg-offset-2">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">Cast Your Vote</h3>
            </div>

            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <h3>{{ poll.question }}</h3>
                    </div>
                </div>

                <div class="row">
                    <div class="col-lg-12">
                        <hr />

                        <form method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="radio">
                                    {% for option in poll.options %}
                                    <label>
                                        <input type="radio" name="poll" value="{{forloop.counter}}" required>
                                        {{ option }}
                                    </label> &nbsp;
                                    {% endfor %}
                                </div>
                            </div>
                            
                            <hr />

                            <button type="submit" class="btn btn-info">
                                Submit
                            </button>
                        </form>
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}